language: php

php:
  - 5.6.4
  - 7.0
  - hhvm

matrix:
    allow_failures:
      - php: hhvm

services:
  - sqlite

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - chmod -R 777 storage/*
  - travis_retry php artisan migrate:install --env=testing --no-interaction

script:
  - composer install
  - php artisan migrate --env=testing --no-interaction
  - vendor/bin/phpunit

notifications:
  email: false

